apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: telemetry-pipeline

  description: Telecom Data Platform Demo

  annotations:
    github.com/project-slug: gauravgoyal86/telecom-data-platform
    backstage.io/kubernetes-id: telemetry-pipeline
    backstage.io/kubernetes-namespace: telemetry
    argocd/app-name: telemetry-pipeline
    janus-idp.io/tekton-enabled: "true"

spec:
  type: service
  lifecycle: production
  owner: guest
